project:
  type: book

engine: jupyter

book:
  title: "Reproducible Polyglot Data Science"
  author: "Bruno Rodrigues"
  date: "2025-12-31"
  search: true
  repo-url: "https://github.com/b-rodrigues/reproducible-data-science"
  repo-actions: [edit, issue]
  repo-branch: "master"
  issue-url: "https://github.com/b-rodrigues/reproducible-data-science/issues"
  sharing: [twitter, facebook]
  downloads: [pdf, epub]
  chapters:
    - index.qmd
    - preface.qmd
    - intro.qmd
    - 02-nix.qmd
    - 03-setup.qmd
    - 04-rix.qmd
    - 05-fp.qmd
    - 06-rixpress.qmd
    - 07-docker.qmd
    - 08-monads.qmd
    - references.qmd
  page-navigation: true

bibliography: references.bib

format:
  epub:
    toc:
      true
    lang:
      en-GB
    date:
      "2025-12-31"
    css:
      epub.css
  html:
    include-in-header:
      file: header.html
    theme:
      light: flatly
      dark: solar
    css:
      epub.css
  pdf:
    keep-tex: true
    documentclass: scrbook
    classoption: [paper=6in:9in,pagesize=pdftex,headinclude=on,footinclude=on,12pt]
    include-in-header:
      text: |
        \usepackage{fvextra}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
        \areaset[0.50in]{4.5in}{8in}
    include-before-body:
      text: |
        \RecustomVerbatimEnvironment{verbatim}{Verbatim}{
           showspaces = false,
           showtabs = false,
           breaksymbolleft={},
           breaklines
           % Note: setting commandchars=\\\{\} here will cause an error
        }
    fig-pos: 'H'
